use_frameworks!

platform :ios, '9.0'

target 'CameraEngine_Example' do
  pod 'CameraEngine', :path => '../'
  pod 'PBJVideoPlayer'
  pod 'FCFileManager'
  pod 'FLAnimatedImage'

  target 'CameraEngine_Tests' do
    inherit! :search_paths

    
  end
end
